### ISSUE TITLE
SSH to multiple servers at a same time from different windows/browsers

### ISSUE THREAD

**Issue by shivup** [roke22/PHP-SSH2-Web-Client#1]
Hello,
First of all, thanks for the great tool.. 
I am having issues when I open this page on multiple browsers/tabs and ssh to same or different servers, they overlap each other.. 
For ex. if I send command in terminal A, it sends command on terminal B, so its not able to distinguish between two different client accessing same socket.. 

Anyone came across same issue and know how to resolve it?

Thanks

**Comment by roke22** [comment]
Hello Shivup,
I will check today, give some time to study and try to fix it.

Thank you!!

**Comment by roke22** [comment]
Please check the new changes, update and test it. Now is working for me but please test it and send me feedback.

Thank you!

**Comment by shivup** [comment]
Awesome.. Its working now.. Thanks a lot.. Appreciate it :+1:
