### ISSUE TITLE
Script works well in CLI but return me an error 500 in web

### ISSUE THREAD

**Issue by Gumbraise** [roke22/PHP-SSH2-Web-Client#10]
Hello, I try to read a file from an external server.
So my script connects well et read the file well BUT when I launch the script on the web the page return me an error 500 Internal Server Error. So someone can tell me why ? And if there's another solution please ?
Thanks lot

**Comment by roke22** [comment]
Hello,

Can you paste the error if the server, you must have a detailed error on
the log of your wbeserver.

Thank you.

**Comment by roke22** [comment]
Gonna close the issue because dont have more information about it.
