### ISSUE TITLE
Print 0 problem fix

### ISSUE THREAD

**Issue by pelandrun** [roke22/PHP-SSH2-Web-Client#11]
Changin line 71 of Servidorsocket.php 
from this
while($line = fgets($this->shell[$from->resourceId])) {
to this
while($line = fgets($this->shell[$from->resourceId]) or $line === 0 or $line === "0") 

and index.html line 126 from this
term.write(data);
to this
//term.write(data);

Hasta luego.

**Comment by roke22** [comment]
Gracias , lo pruebo y lo subo :)

**Comment by roke22** [comment]
No hay error al pintar el cero por pantalla, adjunto imagen para que veas que no da error. Si puedes explicar como reproducir el error que te daba seria de ayuda.

There is no problem printing the zero on the screen, attach is a capture so you can view there is no error. If you can explain how to get the error will be very helpful.

![test-web ssh](https://user-images.githubusercontent.com/5707837/81561773-01088580-9394-11ea-8e15-6e59b1cbf6e4.jpg)
