### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by RoWEN-FCUB** [roke22/PHP-SSH2-Web-Client#13]
Hello. I followed the steps for the installation. Did not find the 'index.php' you mention in : "Modify the url of the websocket in the index.php file." And after I submit the form with the server and login info the screen turns black and shows nothing.

**Comment by roke22** [comment]
Sorry, it is in the index.html line 81

**Comment by RoWEN-FCUB** [comment]
Thanks for the answer. Any hint on the black screen?

**Comment by roke22** [comment]
Check you are reaching the websocket.
Jose J. Anton

**Comment by RoWEN-FCUB** [comment]
I'm getting this error on the console:

PHP Fatal error:  Uncaught Error: Call to undefined function MyApp\ssh2_connect() in /var/www/html/webssh/server/src/Servidorsocket.php:80
Stack trace:
#0 /var/www/html/webssh/server/src/Servidorsocket.php(59): MyApp\Servidorsocket->connectSSH()
#1 /var/www/html/webssh/server/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(75): MyApp\Servidorsocket->onMessage()
#2 /var/www/html/webssh/server/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(131): Ratchet\WebSocket\WsServer->Ratchet\WebSocket\{closure}()
#3 /var/www/html/webssh/server/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\WebSocket\WsServer->Ratchet\WebSocket\{closure}()
#4 /var/www/html/webssh/server/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData()
#5 /var/www/html/webssh/server/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(153): Ratchet\RFC6455\Messaging\MessageBuffer->onData()
#6 /var/www/html/webssh/server/vendor/cboden/ratchet/src/Ratchet/Http/HttpSe in /var/www/html/webssh/server/src/Servidorsocket.php on line 80

Do you speak Spanish?

**Comment by RoWEN-FCUB** [comment]
I've installed php-ssh2, enabled it in php.ini and restarted apache. Now it throws no error but the screen keeps in black and bloked.

**Comment by roke22** [comment]
Solo necesitas tener el websocket corriendo y asegurarte de que la
pagina web conecta correctamente con el websocket. Eso es lo principal.
Jose J. Anton

**Comment by RoWEN-FCUB** [comment]
Despues de que instalé la librería php-ssh2 ahora el websocket inicia pero tampoco me muestra errores. Al menos no en la consola. Podría revisar algo más? Gracias por su respuesta.

**Comment by RoWEN-FCUB** [comment]
Revisando el error.log de php veo que no está cargando la librería phpssh2. Ese debe ser el problema. Seguiré revisando.

**Comment by roke22** [comment]
Cuando ejecutes el websocket este proceso no finaliza nunca y es necesario
para poder utilizar las conexiones ssh
