### ISSUE TITLE
Personal confusion about the principle

### ISSUE THREAD

**Issue by xiaoyan13** [roke22/PHP-SSH2-Web-Client#19]
I know the attach is based on websocket and SSH2, but After I read the code I didn't find anything related to handling ssh decryption on the client side.Is it handled by xterm.js? And it seems that the passwd which input in the login interface is transmitted in clear text（websocket），not use encryption. Can you help me explain the relevant principles, such as where the client's js code encrypts or decrypts the server-encrypted data?
I am a student and recently learning about network protocols and so happened to search for this project. It would be greatly appreciated if you could answer my confusion.Thanks!

**Comment by roke22** [comment]
Hello,
This would be the structure of the project on how it works at the connection level:

  SSH Server --------- Web Server --------- Client

SSH Server is the server where you want to connect
Web Server is the application
Client is the client who visits the website

The connection between the SSH server and the web server is made through the SSH protocol. This is managed in "server/src/Servidorsocket.php", there you can see how there are calls to ssh2_connect

Once the web server is connected to the SSH server, it has to show the information that is displayed by the console to the client and this is also managed in that file but it is done through the websocket.

This can be in plain text if you make the connection through "ws" or encrypted by SSL if you make the connection through "wss".

I hope this resolves your doubts.

**Comment by xiaoyan13** [comment]
Thank you,I got it.
The protocol between the website and server can be selected as wss,which encryptes data by SSL like https when connects to the backend.It is safe.
