### ISSUE TITLE
Terminal width issue

### ISSUE THREAD

**Issue by shivup** [roke22/PHP-SSH2-Web-Client#2]
Hey,
There is one weird bug, not sure if its related to xterm or something else. but when you open terminal, you wont be able to type long shell command there, after certain characters, it goes back at the beginning of the cursor and overwrites things on terminal..  

cols: 80 is default and unable to change that, even if change default value in xterm.js.. for example. cols: 120, still it supports only 80 characters.. So there is a bug somewhere.

Can you please check if that is something you can fix?  

Thanks again.. :+1:

**Comment by roke22** [comment]
That is set on the connect ssh function on the server socket. I changed to 1000 so you can write large commands.

Test it and give me feedback please.
