### ISSUE TITLE
how to init to specific directory?

### ISSUE THREAD

**Issue by marknguyen85** [roke22/PHP-SSH2-Web-Client#4]
When connected to server, how to focus to specific directory?

**Comment by roke22** [comment]
Hello, i dont understarnd your question. Can you explain what are you trying to do?
You are using a ssh connection, if you want to enter to certain directory or have some security you must configure your ssh server.

**Comment by marknguyen85** [comment]
@roke22  
i want to change working dir when connected ex:  to /var/www/ instead defaut directory.

Thanks much.

**Comment by roke22** [comment]
This part is configuration about the user in your linux but maybe you can try to send the command "cd /var/www/" in the auth section.
You have to modify the "/server/src/Servidorsocket.php" file and add between line 57 - 58:

fwrite($this->shell[$from->resourceId],"cd /var/www/");
usleep(800);

Let me know if this work to you. I didnt test it.

Thank you.

**Comment by marknguyen85** [comment]
I did as you instructed and get result here
```
            case 'auth':
                if ($this->connectSSH($data['auth']['server'],$data['auth']['port'],$data['auth']['user'],$data['auth']['password'],$from)){
                    $from->send(mb_convert_encoding("Connected....", "UTF-8"));

                    fwrite($this->shell[$from->resourceId],"cd /var/www/");
                    usleep(800);

                    while($line = fgets($this->shell[$from->resourceId])) {
                        $from->send(mb_convert_encoding($line, "UTF-8"));
                    }

```
and get result 

![image](https://user-images.githubusercontent.com/19941417/50438494-c6c65180-0920-11e9-9c05-eca1c6a01778.png)

**Comment by marknguyen85** [comment]
thanks for support @roke22

**Comment by roke22** [comment]
Remember that this project use the ssh services of the server so if you want to jail the user you must configure your server.
This solution force a command but the user can change the folder.

For jail the user and you have more info at https://www.debian.org/doc/manuals/securing-debian-howto/ap-chroot-ssh-env.en.html
