### ISSUE TITLE
Terminal stays black after submitting form

### ISSUE THREAD

**Issue by nighttimedev** [roke22/PHP-SSH2-Web-Client#7]
![image](https://user-images.githubusercontent.com/39534549/69855405-bb477d00-128b-11ea-90a5-7d7ae2582233.png)

**Comment by roke22** [comment]
Can you try to connect to the remote server from command line without ssh2-web-client? Update with the result.

Thank you.

**Comment by nighttimedev** [comment]
Sure I can. That was the first thing I've tried so that I don't waste your time.

**Comment by roke22** [comment]
Hello,

Run the websocket in a terminal and look if throw some errors or warnings.
Remember that you need to have libssh2

Thank you.

Jose J. Anton

**Comment by roke22** [comment]
is the error fixed?
